<?php

/**
 * @file
 * File containing Drupal module
 */

/**
 * Implements hook_theme().
 */
function d_p_tiles_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_tiles' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_d_image__d_p_tiles' => [
      'base hook' => 'field',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_tiles_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  switch ($bundle) {
    case 'd_p_tiles':
      //$variables['#attached']['library'][] = 'd_p_tiles/justifiedgallery';
      $variables['#attached']['library'][] = 'd_p_tiles/masonry';
      $variables['#attached']['library'][] = 'd_p_tiles/d_p_tiles';
      break;
  }

}
